# Generated by Django 5.0.3 on 2024-03-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamparkSetu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raincheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=2000)),
                ('is_rain', models.BooleanField(default=False)),
            ],
        ),
    ]
