# Generated by Django 4.2.11 on 2024-03-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamparkSetu', '0002_raincheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('listings', models.CharField(max_length=50)),
                ('apartment', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=2000)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
