# Generated by Django 4.2.11 on 2024-03-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamparkSetu', '0003_formmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='apartment',
            field=models.CharField(choices=[(1, '1BHK'), (2, '2BHK'), (3, '3BHK'), (4, 'Other')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='listings',
            field=models.CharField(choices=[(1, 'Buy'), (2, 'Sell'), (3, 'Rent')], default=1, max_length=50),
        ),
    ]
